### ISSUE TITLE
tilemap_runtime.Runtime crashes at comptime when getTextureInfo has a null return_type — supported() @hasDecl gate is insufficient (regression from #703)

### ISSUE THREAD

**Issue by apotema** [labelle-toolkit/labelle-engine#706]
Regression from #703 (tilemap T2 Phase 2). Broke null/generic-backend builds that were green before it — surfaced in labelle-assembler's Examples-integration CI (`asset-streaming-smoke`, a `GfxRendererWith(gfx,...)` game) which last passed 2026-07-05 and fails on current engine main.

## Error
```
src/tilemap_runtime.zig:72:87: error: unable to unwrap null
    const GetInfoRet = @typeInfo(@TypeOf(RenderImpl.getTextureInfo)).@"fn".return_type.?;
```
Reached via `game.zig:237` (`TilemapRuntimeType = if (tilemap_supported) tilemap_runtime.Runtime(RenderImpl) else void`) when instantiated for a backend where `tilemap_supported` is TRUE.

## Root cause
`tilemap_runtime.supported()` (lines 30-37) gates on `@hasDecl(RenderImpl, "getTextureInfo")` — which is true even when `getTextureInfo` is a **generic** function (anytype param or inferred/errorless return). For such a function `@typeInfo(@TypeOf(fn)).@"fn".return_type` is **null**, so line 72's `.?` unwrap traps at comptime. Before #703 this derivation didn't exist, so a generic `getTextureInfo` was harmless; #703 introduced the assumption that it's a concrete fn with a known `return_type` (and same for the `loadTextureFromMemory` derivation at line 68 — audit it too). The `game.zig` field gate is correct; the bug is that `supported()` returns true for a shape the `Runtime(...)` body can't actually consume.

## Fix options
1. Tighten `supported()`: additionally require `getTextureInfo` (and `loadTextureFromMemory`) to be NON-generic — e.g. `@typeInfo(@TypeOf(RenderImpl.getTextureInfo)).@"fn".return_type != null`. Then the affected backend falls back to tilemap-unsupported (`TilemapRuntimeType = void`) instead of crashing. Simplest; matches the existing capability-gate philosophy.
2. If those backends SHOULD support tilemaps (asset-streaming-smoke presumably wants them), make their `getTextureInfo` a concrete-signature fn so `return_type` resolves — the real fix if the generic signature is incidental.

Decide per whether the failing backend is meant to support tilemaps. Add a stub-backend regression test (`Runtime()` instantiated against a RenderImpl whose getTextureInfo is generic → must resolve to void, not crash).

## Blast radius
Every null/generic-backend build on current engine main: the assembler Examples-integration suite, and likely the `examples/packs-demo` wall-probe fixture (null backend) from assembler#498's CI. Worth confirming packs-demo CI is red too.

**Comment by apotema** [comment]
Fixed by #707 (engine v1.75.1, fb882fe): `supported()` now gates on `hasReflectableSeam()` so a backend whose `getTextureInfo` is legitimately generic (the correct `GfxRendererWith` design — `?@TypeOf(self.inner).TextureInfo`) falls back to `TilemapRuntimeType = void` instead of comptime-crashing on the null return_type. Confirmed root cause: gfx's generic seam is correct; the engine gate was too naive (@hasDecl-only). Unblocks null/headless builds (assembler examples, packs-demo probes).
